Iter13
pochtalexa/ya-practicum-metrics pull request #13
Opened 2023-10-23 07:59 UTC by pochtalexa

2023-10-24 09:00 UTC, s-shpak requested changes

2023-10-24 09:00 UTC, s-shpak commented on .gitignore
> +docker/
У тебя все равно запушилась вся БД в репозиторий, ее надо из репозитория убрать. Здесь описана команда для этого: https://www.git-tower.com/learn/git/commands/git-rm

2023-10-24 09:00 UTC, s-shpak commented on .gitignore
> +*.log
`client.log` попал в репозиторий

2023-10-24 09:00 UTC, s-shpak commented on cmd/agent/main.go
> +	//"github.com/avast/retry-go"
Такие комментарии надо убирать из PR

2023-10-24 09:00 UTC, s-shpak commented on cmd/agent/main.go
> +				err = metrics.SendMetricBatch(CashMetrics, httpClient, reportRunAddr)
Не совсем ясно, почему метрики отправляются два раза

2023-10-24 09:00 UTC, s-shpak commented on cmd/agent/main.go
>  				panic(err)
Это, конечно, не относится к этому PR, но паниковать не нужно практически никогда: надо прокидывать необрабатываемую ошибку на самый верхний уровень и там завершать выполнение программы при помощи `log.Fatal` (который под капотом вызовет что-то типа `os.Exit(1)`)

2023-10-24 09:00 UTC, s-shpak commented on cmd/server/main.go
> +	db         *sql.DB
Хендлер к БД лучше инициализировать в пакете `storage`: этот слой вообще не должен о нем знать. Вам рассказывали про слоенную архитектуру?

2023-10-24 09:00 UTC, s-shpak commented on cmd/server/main.go
> +// TODO нужно ли здесь оборачивать в retry?
Можно, но не обязательно (я бы не стал, т.к. в учебном задании это не требуется)

2023-10-24 09:00 UTC, s-shpak commented on cmd/server/main.go
> +			panic(err)
Не надо паниковать

2023-10-24 09:00 UTC, s-shpak commented on cmd/server/main.go
> +		err := storage.StoreMetricsToDB(DBstorage)
Зачем определять две разные функции, если можно определить один интерфейс стора (с методом `StoreMetrics`) и, в зависимости от конфигурации, образаться к БД или к файловой системе ?

2023-10-24 09:00 UTC, s-shpak commented on cmd/server/main.go
> +			handlers.RootHandler(w, r, DBstorage)
Поробуй не дублировать логику таким образом: что случится, если ты решишь добавить другие типы сторов? В идеале, такое добавление не должно ничего менять в хендлерах

2023-10-24 09:00 UTC, s-shpak commented on cmd/server/main.go
> +			log.Info().Err(err).Msg("DB conn error")
Стоит ли продолжать выполнение программы при возникновении такой ошибки?

2023-10-24 09:00 UTC, s-shpak commented on docker/docker-compose.yml
А этот файл можно оставить в репозитории, чтобы было проще тестировать локально

2023-10-24 09:00 UTC, s-shpak commented on internal/agent/metrics/send.go
> +		log.Info().Err(err).Str("reqBody", string(reqBody)).Msg("Marshal Batch error")
Зачем логировать здесь? Ошибку лучше прокинуть до HTTP-хендлера и залогировать там

2023-10-24 09:00 UTC, s-shpak commented on internal/agent/metrics/send.go
> +	//dec := json.NewDecoder(res.Body)
Такие комментарии надо удаять из кода

2023-10-24 09:00 UTC, s-shpak commented on internal/agent/metrics/send.go
> +			return retry.RetryableError(err)
Здесь ты не должен знать об использовании `retry` - лучше принимать решение о том, что действие можно повторить, на уровне выше (либо перенести `retry` сюда)

2023-10-24 09:00 UTC, s-shpak commented on internal/server/storage/db.go
> +	DBconn *sql.DB
Я бы посоветовал тебе использовать `pgx` напрямую. И, кроме того, использовать пул соединений вместо обычного хендлера

2023-10-24 09:00 UTC, s-shpak commented on internal/server/storage/db.go
> +	gaugeTable := `CREATE TABLE IF NOT EXISTS gauge (
Вы не разбирали механизм миграций?

2023-10-24 09:00 UTC, s-shpak commented on internal/server/storage/db.go
> +			return retry.RetryableError(err)
А как ты решил, что в случае этой ошибки (или других ошибок в методах в этом файле) действие надо повторить?

2023-10-24 18:49 UTC, pochtalexa commented on cmd/agent/main.go
> +				err = metrics.SendMetricBatch(CashMetrics, httpClient, reportRunAddr)
метрики отправляются на разные енд-поинты:
/update/ - по одной
/updates/ - батчем

2023-10-25 15:20 UTC, pochtalexa commented on internal/agent/metrics/send.go
> +		log.Info().Err(err).Str("reqBody", string(reqBody)).Msg("Marshal Batch error")
Как тогда понять, на каком именно этапе процесса отправки произошла ошибка?

2023-10-25 15:53 UTC, pochtalexa commented on internal/server/storage/db.go
> +	DBconn *sql.DB
принято на будущее. сейчас дефицит ресурса для тюнинга

2023-10-27 09:58 UTC, s-shpak commented on cmd/agent/main.go
> +				err = metrics.SendMetricBatch(CashMetrics, httpClient, reportRunAddr)
Это правда, но зачем? Почему недостаточно отправить метрику один раз батчем?

2023-10-27 09:59 UTC, s-shpak commented on internal/agent/metrics/send.go
> +		log.Info().Err(err).Str("reqBody", string(reqBody)).Msg("Marshal Batch error")
На каждом уровне ты можешь добавить к тексту ошибки какую-то информацию, и такми образом собрать такой "ad-hoc" stack-trace

2023-10-27 10:02 UTC, s-shpak requested changes
Посмотри на два комментария, которые я оставил. Также выдай мне, пожалуйста, права на запись в репо, чтобы я мог резолвить комментарии, и не резолвь их сам - это должен делать ревьюер

2023-10-27 10:41 UTC, pochtalexa commented on cmd/agent/main.go
> +				err = metrics.SendMetricBatch(CashMetrics, httpClient, reportRunAddr)
Да, кажется, что достаточно - я сначала и убрал "старый" способ отправки метрик - но тесты стали падать. Спросил в Пачке - там сказали, нужно оставить оба способа отправки. Поэтому оба и оставил.

2023-10-27 16:02 UTC, pochtalexa commented on internal/agent/metrics/send.go
> +		log.Info().Err(err).Str("reqBody", string(reqBody)).Msg("Marshal Batch error")
да, попробовал, так даже удобней

2023-10-28 16:12 UTC, s-shpak requested changes

2023-10-28 16:12 UTC, s-shpak commented on internal/server/storage/db.go
> +func (d *DBstore) UpdateMetricBatch(reqJSON []models.Metrics) error {
Я это просмотрел, сорри. Батчинг это другое: это запсиь сразу многих значений в одном запросе к БД.

Здесь можно посмотреть как это реализовано: https://stackoverflow.com/questions/12486436/how-do-i-batch-sql-statements-with-package-database-sql

2023-10-30 14:18 UTC, s-shpak approved these changes
LGTM!

2023-10-31 15:42 UTC, merged