Iter15
pochtalexa/ya-practicum-metrics pull request #15
Opened 2023-11-03 13:46 UTC by pochtalexa

2023-11-03 21:58 UTC, s-shpak requested changes

2023-11-03 21:58 UTC, s-shpak commented on cmd/agent/main.go
> +		for range time.Tick(time.Second * time.Duration(pollInterval)) {
Лучше правильный Duration высчитывать при получении конфига, т.к. если в будущем секунды поменяются на, например, миллисекунду, то нам надо будет незабыть поправить рассчет во всех местах, где эти значения используются

2023-11-03 21:58 UTC, s-shpak commented on cmd/agent/main.go
> +	chCashMetrics := make(chan models.Metric, 100)
1. Почему 100, откуда это значение?
2. Если канал забъется, то мы зависнем. Как это можно решить?

2023-11-03 21:58 UTC, s-shpak commented on cmd/agent/main.go
> +			CashMetrics, err = metrics.CollectMetrics(runtimeStorage, gopsutilStorage)
```suggestion
			cashMetrics, err = metrics.CollectMetrics(runtimeStorage, gopsutilStorage)
```

2023-11-03 21:58 UTC, s-shpak commented on cmd/agent/main.go
> +				chCashMetrics <- v
Почему не отправлять метрики батчем?

2023-11-03 21:58 UTC, s-shpak commented on cmd/agent/main.go
> +			go func() {
Зачем эта горутина?

2023-11-03 21:58 UTC, s-shpak commented on internal/agent/metrics/metrics.go
> +	el.CPUutilization, _ = cpu.Percent(10*time.Millisecond, true)
Ошибки надо проверять

2023-11-03 21:58 UTC, s-shpak commented on internal/server/handlers/handlers.go
> +	body, _ := io.ReadAll(r.Body)
Ошибки надо проверять

2023-11-03 21:58 UTC, s-shpak commented on internal/server/handlers/handlers.go
> +func checkReqBodySign(reqHeaderHash string, r *http.Request) bool {
Это лучше сделать `middleware`

2023-11-05 15:22 UTC, pochtalexa commented on cmd/agent/main.go
> +		for range time.Tick(time.Second * time.Duration(pollInterval)) {
скорректировал

2023-11-05 15:48 UTC, pochtalexa commented on cmd/agent/main.go
> +	chCashMetrics := make(chan models.Metric, 100)
как вариант, добавил select

2023-11-05 15:52 UTC, pochtalexa commented on cmd/agent/main.go
> +	chCashMetrics := make(chan models.Metric, 100)
100 - для трех наборов метрик. если их не успеваем отправить - значит какие-то проблемы при отпавке.

2023-11-05 15:52 UTC, pochtalexa commented on cmd/agent/main.go
> +			CashMetrics, err = metrics.CollectMetrics(runtimeStorage, gopsutilStorage)
тут не понял - какое замечание?

2023-11-05 15:58 UTC, pochtalexa commented on cmd/agent/main.go
> +				chCashMetrics <- v
на сервере два енд-поинта - один принимает метрики "по одной", другой - батчем
для отправки метрик на каждый из енд-поинтов - созданы отдельные горутины: по одной и батчем.

Кажется, что можно было бы оставить один способ отправки - батчем. Но в задании было сказано, что необходимо сохранить обратную совместимость. И как обсуждали в Пачке - нужно оставить два способа.

2023-11-05 16:00 UTC, pochtalexa commented on cmd/agent/main.go
> +			go func() {
если вопрос по SendMetricBatch
то комментарий выше

2023-11-05 16:23 UTC, pochtalexa commented on internal/agent/metrics/metrics.go
> +	el.CPUutilization, _ = cpu.Percent(10*time.Millisecond, true)
скорректировал

2023-11-05 16:29 UTC, pochtalexa commented on internal/server/handlers/handlers.go
> +	body, _ := io.ReadAll(r.Body)
скорректировал

2023-11-08 07:57 UTC, pochtalexa commented on internal/server/handlers/handlers.go
> +func checkReqBodySign(reqHeaderHash string, r *http.Request) bool {
перенес gzip и checkReqBodySign  в middleware

2023-11-08 15:26 UTC, s-shpak commented on cmd/agent/main.go
> +				chCashMetrics <- v
Обратная совместимость - характеристика сервера: старые версии агентов должны работать с новыми вресиями сервера. Таким образом на агентах можно оставить только один способ отправки. Но если в пачке пришли к консенсусу, что нужно отправлять двумя способами, то просто зарезолвь этот коммент

2023-11-08 15:27 UTC, s-shpak commented on cmd/agent/main.go
> +			CashMetrics, err = metrics.CollectMetrics(runtimeStorage, gopsutilStorage)
В Го переменные пишутся с маленькой буквы

2023-11-08 15:28 UTC, s-shpak commented on cmd/agent/main.go
> +	chCashMetrics := make(chan models.Metric, 100)
Принцип должен быть следующим:
1. одна горутина собирает метрики
2. пеередает их другой
3. другая либо отдает отправителю, либо, если отправитель занят (rate limiting), то дропает их

Проблемы при отправке не должны подвешивать сервис, их надо обрабатывать

2023-11-08 15:28 UTC, s-shpak requested changes
См. комментарии

2023-11-09 16:56 UTC, pochtalexa commented on cmd/agent/main.go
> +			CashMetrics, err = metrics.CollectMetrics(runtimeStorage, gopsutilStorage)
скорректировано

2023-11-10 13:48 UTC, pochtalexa commented on cmd/agent/main.go
> +	chCashMetrics := make(chan models.Metric, 100)
скорректировано

2023-11-13 19:09 UTC, s-shpak approved these changes

2023-11-14 08:09 UTC, merged