Iter9
pochtalexa/ya-practicum-metrics pull request #9
Opened 2023-10-04 17:46 UTC by pochtalexa

2023-10-05 08:25 UTC, gonozov0 requested changes
Прекрасная работа, очень круто, что уже на заиспользовал горутины и каналы 👍
Оставил пару комментариев по улучшению кода

2023-10-05 08:25 UTC, gonozov0 commented on cmd/agent/main.go
> +	//httpClient := *http.DefaultClient
Старайся сразу удалять лишний код, а не комметировать, чтобы не было таких сюрпризов на ревью. Благодаря гиту удаленный код все равно легко вернуть

2023-10-05 08:25 UTC, gonozov0 commented on cmd/server/main.go
> +	//mux.Use(middleware.Logger)
Почему решил убрать middleware с логированием запросов?

2023-10-05 08:25 UTC, gonozov0 commented on internal/agent/send/send.go
> +func Metrics(metrics *metrics.RuntimeMetrics, reportRunAddr string) error {
Это вроде уже нигде не используется

2023-10-05 08:25 UTC, gonozov0 commented on internal/server/handlers/handlers_test.go
> +
Вроде абсолютно одинаковые структуры, почему просто не импортишь из models?

2023-10-05 08:25 UTC, gonozov0 commented on internal/server/storage/interface.go
> +	StoreMetricsToFile() error
Не стоит расширять этим методом интерфейс, т.к. для реализации DBStorage нам он не будет нужен

2023-10-05 08:25 UTC, gonozov0 commented on cmd/server/main.go
> +	os.Exit(0)
Очень круто, что уже обработал кейс с сохранением метрик при завершении процесса, но вызывать os.Exit(0) в горутине все таки неправильно.

Для сдачи этой работы можно оставить, как есть, но в будущих итерациях подумать, как отлавливать этот сигнал в основном потоке, останавливать сервер и только потом записывать в файл.

2023-10-05 11:49 UTC, pochtalexa commented on internal/server/handlers/handlers_test.go
> +
все же немного разные
отличаются от models
metricsSend - без указателей
metricsSendBad - все значения - строковые

2023-10-06 06:49 UTC, gonozov0 approved these changes
Все критичные моменты поправлены, апрув 👍

2023-10-06 11:30 UTC, merged